export enum RelationshipType {
  Association = 'association',
  Serving = 'serving',
  UsedBy = 'usedby',
  Assignment = 'assignment',
  Triggering = 'triggering',
  Access = 'access',
  Influence = 'influence',
  Realization = 'realization',
  Realisation = 'realisation',
  Specialization = 'specialization',
  Flow = 'flow',
  Composition = 'composition',
  Aggregation = 'aggregation',
}
