export enum RelationshipType {
  Association = 'Association',
  Serving = 'Serving',
  UsedBy = 'UsedBy',
  Assignment = 'Assignment',
  Triggering = 'Triggering',
  Access = 'Access',
  Influence = 'Influence',
  Realization = 'Realization',
  Realisation = 'Realisation',
  Specialization = 'Specialization',
  Flow = 'Flow',
  Composition = 'Composition',
  Aggregation = 'Aggregation',
}
