checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 5
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 125
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
exclude_patterns:
  - '__tests__/'
  - '**/node_modules/'